### ISSUE TITLE
Error, cant execute

### ISSUE THREAD

**Issue by OfficialZygorg** [davidwhitman/VRAM_Calculator#2]
Error: unable to access jarfile ./VRAM-Counter.jar
Press any key to continue . . .

**Comment by wispborne** [comment]
@OfficialZygorg 

How did you download VRAM_Calculator? Did you download the latest .zip file from releases?
(https://github.com/davidwhitman/VRAM_Calculator/releases/download/1.4.0/VRAM-Counter-1.4.0.zip)

If you downloaded the source code instead of a release, you'd get that error because `VRAM-Counter.jar` doesn't exist in the source code.

If it's not that, can you provide more details?
Are you using Windows? Which version? 
Did you launch it by double-clicking the .bat file?

**Comment by OfficialZygorg** [comment]
I did download the source code directly, soo that maybe what's happening
I'll try later if that's the case, because its dinner time

**Comment by OfficialZygorg** [comment]
Ok, it was because i downloaded the source code without the .jar instead of the release. Sorry for bothering ya
